# Site settings
title: Kisallioppiminen.fi
backendbaseurl: "https://kisallioppiminen.github.io/"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

encoding: UTF-8
sass:
  style: :compressed

navigation:
  "Materiaalit": "/"
  "Blogi": "http://blogs.helsinki.fi/kisallioppiminenlukiossa"
  "Tietoa": "/tietoa.html"
  "BETA": "https://beta-kisallioppiminen.github.io"
  # Login button added with js

resources:
  css:
    - "/css/bootstrap.css"
    - "/css/custom.css"
    - "//fonts.googleapis.com/css?family=Alegreya+Sans:400|Noto+Sans:400,700|Open+Sans+Condensed:300,700"
    - "/css/main.css"
   #- "/css/definitions_page.css"

  js:
    # Download libraries
    - "//code.jquery.com/jquery-2.2.4.min.js"
    - "//code.jquery.com/ui/1.12.1/jquery-ui.min.js"
    - "//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"

    # Download own scripts
    - "/js/common.js"
    - "/js/session.js"
    - "/js/view.js"
    - "/js/scheduleManager.js"
    - "/js/exercises.js"
    - "/js/backend.js"
    - "/js/jquery-ui.js"
    - "/js/mooc.js"
    - "/js/button/button.js"
    - "/js/statistics.js"
    - "/js/scheduleCheckbox.js"
    - "/js/init.js"



exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
